Dependend python packages updated
lugfl/website pull request #2
Opened 2019-03-10 09:35 UTC by fager

fix #1

2019-03-24 09:27 UTC, jokey2k requested changes
Generally ok, may need this tweak

2019-03-24 09:27 UTC, jokey2k commented on requirements.txt
> +tornado==6.0.1
tornado 6.0.2 has a fix for
WebSocketHandler.set_nodelay
which may be helpful here

2019-03-24 11:32 UTC, jan-lugfl approved these changes
looks good to me, without actually testing it

2019-10-27 11:07 UTC, jan-lugfl commented
fixed by 933f0cad7b868186114a3fae594e13341101147d

2019-10-27 11:07 UTC, closed without merging